apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sw340y3sq-go
  janus-idp.io/tekton: sw340y3sq-go
  backstage.io/kubernetes-id: sw340y3sq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sw340y3sq-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
